### PR TITLE
Improve bot detection regex

### PR DESCRIPTION
**Pull request by lencioni**
This pull request improves the bot detection regex by:
- adding a number of missing strings, such as alexa, facebookexternalhit, feedburner, google web preview, nagios, postrank, pingdom, slurp, yahoo!, and yandex
- removing redundant strings such as googlebot and robot (redundant because of the inclusion of a general "bot" string)
- consolidating similar strings ("crawler" and "crawling" became "crawl(er|ing)")
- alphabetizing the list of bots

### CODE REVIEW

**Comment by lencioni** [comment]
It looks like this may address Issues #14 and #18

**Comment by ghost** [comment]
This would be helpful to us at Causes.

**Comment by twobitlabs** [comment]
+1 for this!

**Comment by kevinelliott** [comment]
I'll get this tested and merged in very soon!

**Pull request merged**
