### PR TITLE
Added support for is_mobile? returning true for Google's smartphone crawler

### PR DESCRIPTION
**Pull request by twobitlabs**
Google has both desktop and mobile crawlers:

https://developers.google.com/webmasters/smartphone-sites/googlebot-mobile

This change makes it so is_mobile? returns true AND is_bot? returns true for the Google smartphone crawler and includes specs for both the desktop and mobile user agent. I opted to stay backwards compatible for the standard Google crawler user agent so that is_computer? continues to return false.

### CODE REVIEW

**Comment by kevinelliott** [comment]
Looks good, I'll get this merged in shortly. Thanks for the contribution!

**Comment by kevinelliott** [comment]
@thuss There were major changes in a PR previous to yours, and now this PR can no longer be automatically merged. Can you pull in develop and resubmit?

**Comment by twobitlabs** [comment]
I had also merged in Joe's changes so let me create a new feature branch and submit a new pull request.

**Comment by kevinelliott** [comment]
Oh that's makes sense. Thanks for doing that.

**Pull request closed without merging**
