### PR TITLE
Improved Bot Detection

### PR DESCRIPTION
**Pull request by joshuasiler**
Dramatically improved bot detection capabilities. Added rake test. Fixed some crashy bugs with nil values in some user_agents. Incremented gem version.

### CODE REVIEW

**Comment by kevinelliott** [comment]
Thanks for the improvements. Before I can merge this in, a few things need to be changed:
- Remove the komodo file, as that is unique to your environment
- Revert the change to Rakefile, since I wish to keep the bundler gem tasks (more specifically, find a way to include your new task as a lib/tasks/.rake file if possible)

Please submit a new pull request once you've made the improvements above. I will have to manually merge since I've already merged in another pull request, but the change is quite minor.

I appreciate the contribution!

-Kevin

**Comment by joshuasiler** [comment]
Removed. Also cleaned up rake tasks as requested

**Comment by davidjrice** [comment]
Nice one, will give this a try. Will see if this improves things for Issue #3

**Comment by joshuasiler** [comment]
It's going to need a bit of a refactor to get any better. Right now it's only looking in parsed "comments" part of the string, which doesn't exist in all cases.

**Comment by kevinelliott** [comment]
Great job! Let me review the changes, make a few minor changes for consistency, and merge it in. Thanks guys.

**Pull request merged**
